# Generated by Django 6.0.2 on 2026-03-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai_ml', 'AI/ML'), ('tools', 'Tools & DevOps'), ('other', 'Other')], max_length=50)),
                ('level', models.IntegerField(default=50, help_text='Skill level percentage (1-100)')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name or SVG path', max_length=50, null=True)),
            ],
        ),
    ]
