# Generated by Django 6.0.2 on 2026-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("stars", models.IntegerField(default=0)),
                ("url", models.URLField()),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
            ],
        ),
    ]
